apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid
  labels:
    app: covid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid
  template:
    metadata:
      labels:
        app: covid
    spec:
      containers:
      - name: covid
        image: "localhost:32000/covid:3b52162e"
        env:
        - name: "SERVER_SERVLET_CONTEXT_PATH"
          value: "/covid"
        ports:
        - name: http
          containerPort: 8080
